#%%
# Figure 05: Gaussian random-frequency robustness

#%%
# Imports and project paths
import csv
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

CURRENT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = CURRENT_DIR.parent
SRC_DIR = PROJECT_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from common_utils import save_metadata
from figure_style import apply_paper_style, format_axes, save_figure_all_formats

apply_paper_style()
plt.rcParams.update(
    {
        "font.size": 17,
        "axes.labelsize": 19,
        "xtick.labelsize": 15,
        "ytick.labelsize": 15,
        "legend.fontsize": 14,
    }
)

#%%
# Paths and layout controls
SEEDS = np.arange(5)
DRIFT_K_VALUES = np.array([8.0, 10.0, 12.0])
DRIFT_SIGMA_VALUES = np.array([0.16, 0.20, 0.24])
HITTING_K_VALUES = np.array([6.0, 7.5, 9.0, 10.5, 12.0])
HITTING_SIGMA_VALUES = np.array([0.20, 0.24, 0.28, 0.32, 0.36])

FIGURE_DIR = PROJECT_ROOT / "figures"
CACHE_DIR = PROJECT_ROOT / "data" / "cache"
SUMMARY_DIR = PROJECT_ROOT / "data" / "processed"
for directory in (FIGURE_DIR, CACHE_DIR, SUMMARY_DIR):
    directory.mkdir(parents=True, exist_ok=True)

DRIFT_CACHE = CACHE_DIR / "fig03_slow_polar_drift_gaussian_3x3_seeds0-4.npz"
HITTING_CACHE = CACHE_DIR / "fig04_hitting_time_gaussian_5x5_seeds0-4.npz"
SUMMARY_FILE = SUMMARY_DIR / "summary_exp05_gaussian_robustness.csv"
METADATA_FILE = SUMMARY_DIR / "metadata_exp05_gaussian_robustness.json"
FIGURE_STEM = "fig5_gaussian_robustness"

FIGSIZE = (7.8, 4.5)
LEFT, RIGHT, BOTTOM, TOP, WSPACE = 0.12, 0.965, 0.30, 0.91, 0.36
PANEL_LABEL_Y = -0.25
PANEL_LABEL_FONTSIZE = 17
XLABEL_PAD = 4
YLABEL_PAD = 4
LEGEND_FONTSIZE = 13

#%%
# Load Gaussian robustness caches generated by Figures 3 and 4.
missing = [path for path in (DRIFT_CACHE, HITTING_CACHE) if not path.exists()]
if missing:
    missing_text = "\n".join(str(path) for path in missing)
    raise FileNotFoundError(
        "Missing Gaussian robustness cache(s):\n"
        f"{missing_text}\n"
        "Generate the Gaussian modes in fig03_slow_polar_drift.py and "
        "fig04_hitting_time.py first."
    )

drift_data = dict(np.load(DRIFT_CACHE))
hitting_data = dict(np.load(HITTING_CACHE))
print("Loaded:", DRIFT_CACHE)
print("Loaded:", HITTING_CACHE)

#%%
# Diagnostics and compact summary files
drift_ratio = np.asarray(drift_data["panel_b_D_meas_over_Lambda_K"], dtype=float)
drift_error = np.asarray(drift_data["panel_b_relative_drift_error"], dtype=float)
hitting_valid = np.isfinite(hitting_data["T_pred"]) & np.isfinite(hitting_data["T_sim"])
hitting_relative = np.asarray(hitting_data["relative_error"], dtype=float)
hitting_relative = hitting_relative[np.isfinite(hitting_relative)]

summary_rows = [
    {
        "panel": "a_drift_rate",
        "num_points": len(drift_data["panel_b_D_meas"]),
        "ratio_or_relative_error_min": float(np.min(drift_ratio)),
        "ratio_or_relative_error_max": float(np.max(drift_ratio)),
        "ratio_or_relative_error_mean": float(np.mean(drift_ratio)),
        "maximum_absolute_error": float(np.max(drift_error)),
    },
    {
        "panel": "b_hitting_time",
        "num_points": int(np.sum(hitting_valid)),
        "ratio_or_relative_error_min": float(np.min(hitting_relative)),
        "ratio_or_relative_error_max": float(np.max(hitting_relative)),
        "ratio_or_relative_error_mean": float(np.mean(hitting_relative)),
        "maximum_absolute_error": float(
            np.max(np.abs(hitting_data["T_sim"][hitting_valid] - hitting_data["T_pred"][hitting_valid]))
        ),
    },
]
with SUMMARY_FILE.open("w", newline="", encoding="utf-8") as stream:
    writer = csv.DictWriter(stream, fieldnames=list(summary_rows[0]))
    writer.writeheader()
    writer.writerows(summary_rows)

save_metadata(
    METADATA_FILE,
    {
        "figure": "Figure 5 Gaussian robustness",
        "figure_stem": FIGURE_STEM,
        "seeds": SEEDS,
        "drift_cache": DRIFT_CACHE.relative_to(PROJECT_ROOT),
        "hitting_cache": HITTING_CACHE.relative_to(PROJECT_ROOT),
        "drift_K_values": DRIFT_K_VALUES,
        "drift_sigma_values": DRIFT_SIGMA_VALUES,
        "hitting_K_values": HITTING_K_VALUES,
        "hitting_sigma_values": HITTING_SIGMA_VALUES,
        "drift_D_over_Lambda_min": float(np.min(drift_ratio)),
        "drift_D_over_Lambda_max": float(np.max(drift_ratio)),
        "drift_D_over_Lambda_mean": float(np.mean(drift_ratio)),
        "hitting_relative_error_min": float(np.min(hitting_relative)),
        "hitting_relative_error_max": float(np.max(hitting_relative)),
        "hitting_relative_error_mean": float(np.mean(hitting_relative)),
    },
)
print("Saved:", SUMMARY_FILE)
print("Saved:", METADATA_FILE)

#%%
# Plot the two Gaussian robustness diagnostics.
fig, axes = plt.subplots(1, 2, figsize=FIGSIZE)
ax_a, ax_b = axes
colors = ["#0072B2", "#D55E00", "#009E73"]
markers = {8.0: "o", 10.0: "s", 12.0: "^"}

# Panel (a): Gaussian D_meas versus Lambda_K.
for j, K in enumerate(DRIFT_K_VALUES):
    mask = np.isclose(drift_data["panel_b_K"], K)
    ax_a.scatter(
        drift_data["panel_b_Lambda_K"][mask],
        drift_data["panel_b_D_meas"][mask],
        marker=markers[K],
        s=58,
        color=colors[j],
        alpha=0.70,
        edgecolors="black",
        linewidths=0.7,
        label=rf"$K={K:g}$",
        zorder=3,
    )
drift_lo = min(
    float(np.min(drift_data["panel_b_Lambda_K"])),
    float(np.min(drift_data["panel_b_D_meas"])),
)
drift_hi = max(
    float(np.max(drift_data["panel_b_Lambda_K"])),
    float(np.max(drift_data["panel_b_D_meas"])),
)
drift_pad = 0.09 * (drift_hi - drift_lo)
ax_a.plot(
    [drift_lo - drift_pad, drift_hi + drift_pad],
    [drift_lo - drift_pad, drift_hi + drift_pad],
    "k--",
    linewidth=1.8,
    zorder=2,
)
ax_a.set(
    xlabel=r"$\Lambda_K$",
    ylabel=r"$D_{\mathrm{meas}}$",
    xlim=(drift_lo - drift_pad, drift_hi + drift_pad),
    ylim=(drift_lo - drift_pad, drift_hi + drift_pad),
)
common_ticks = np.array([2.0e-3, 3.0e-3, 4.0e-3, 5.0e-3, 6.0e-3, 7.0e-3])
ax_a.set_xticks(common_ticks)
ax_a.set_yticks(common_ticks)
ax_a.legend(
    loc="upper left",
    fontsize=LEGEND_FONTSIZE,
    frameon=False,
    handlelength=1.2,
    labelspacing=0.35,
    borderaxespad=0.4,
)
ax_a.set_aspect("equal", adjustable="box")

# Panel (b): Gaussian predicted versus simulated hitting times.
ax_b.scatter(
    hitting_data["T_pred"][hitting_valid],
    hitting_data["T_sim"][hitting_valid],
    color="#0072B2",
    s=48,
    edgecolors="black",
    linewidths=0.7,
)
ax_b.plot([0, 20], [0, 20], "k--", linewidth=1.8)
ax_b.set(
    xlabel=r"$T_\eta^{\mathrm{pred}}$",
    ylabel=r"$T_\eta^{\mathrm{sim}}$",
    xlim=(0, 20),
    ylim=(0, 20),
)
ax_b.set_xticks([0, 5, 10, 15, 20])
ax_b.set_yticks([5, 10, 15, 20])
ax_b.set_aspect("equal", adjustable="box")

for label, ax in zip(("(a)", "(b)"), axes):
    ax.xaxis.labelpad = XLABEL_PAD
    ax.yaxis.labelpad = YLABEL_PAD
    format_axes(ax)
    ax.text(
        0.5,
        PANEL_LABEL_Y,
        label,
        transform=ax.transAxes,
        ha="center",
        va="top",
        fontsize=PANEL_LABEL_FONTSIZE,
    )
fig.subplots_adjust(left=LEFT, right=RIGHT, bottom=BOTTOM, top=TOP, wspace=WSPACE)

#%%
# Save and show
saved_paths = save_figure_all_formats(fig, FIGURE_DIR, FIGURE_STEM)
print("Saved:", *saved_paths, sep="\n")
plt.close(fig)

# %%
